stages:
  - build

build:
  stage: build
  image: adoptopenjdk/openjdk11
  script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - echo start Build
    - ./gradlew build
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches